const $=id=>document.getElementById(id);const guest=new URLSearchParams(location.search).get('to')||'Tamu Undangan';
const loading=$('loading'),start=$('start'),scene=$('scene'),m1=$('m1'),m2=$('m2'),vn=$('vn');let song=1,lampOn=true;
let progress=0;const pt=setInterval(()=>{progress+=2;$('barFill').style.width=progress+'%';$('pct').textContent=progress+'%';if(progress>=100){clearInterval(pt);loading.classList.add('open');setTimeout(()=>{loading.classList.add('hidden');start.classList.remove('hidden')},1200)}},55);
$('startBtn').onclick=()=>{start.classList.add('hidden');scene.classList.remove('hidden');m1.play().catch(()=>{});m1.onended=()=>m2.play().catch(()=>{});m2.onended=()=>m1.play().catch(()=>{});setTimeout(()=>$('hand').classList.add('hidden'),5200)};
$('musicBtn').onclick=()=>{let a=m1.paused?m2:m1;a.paused?a.play().catch(()=>{}):a.pause()};
function popup(title,body,art){$('popupArt').innerHTML=art?`<img src="assets/${art}" alt="">`:'';$('popupBody').innerHTML=`<h2>${title}</h2>${body}`;$('backdrop').classList.remove('hidden')};
$('close').onclick=()=>{$('backdrop').classList.add('hidden');vn.pause();m1.volume=m2.volume=1};$('backdrop').onclick=e=>{if(e.target===e.currentTarget)$('close').click()};
function hot(id,x,y,w,h){const b=document.createElement('button');b.className='hot';b.style=`left:${x}px;top:${y}px;width:${w}px;height:${h}px`;b.onclick=()=>act(id);scene.appendChild(b)}
// Coordinates follow the actual full-canvas asset alpha bounds (1081x1920).
const sx=()=>innerWidth/1081,sy=()=>innerHeight/1920;function addHot(id,b){hot(id,b[0]*sx(),b[1]*sy(),(b[2]-b[0])*sx(),(b[3]-b[1])*sy())}
addHot('couple',[642,341,870,763]);addHot('story',[197,755,381,981]);addHot('date',[799,1217,1081,1487]);addHot('gallery',[166,326,298,391]);addHot('gift',[756,1504,1036,1887]);addHot('rsvp',[704,941,1037,1138]);addHot('chair',[305,1104,820,1782]);
$('lampHot').style='left:0;top:0;width:100%;height:160px';$('lampHot').onclick=()=>{lampOn=!lampOn;$('lampImg').src=lampOn?'assets/LAMPU DEKOR UTAMA.png':'assets/LAMPU DEKOR MATI.png';$('lampGlow').style.opacity=lampOn?1:0};
function act(id){if(id==='couple')popup('Hai, '+guest,`<div>Berawal dari kabar bahagia yang ingin kami bagikan. Dengan penuh kebahagiaan, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir dan turut memberikan doa restu pada acara pernikahan kami.</div><p><b>Syahfardan Al Hilal Havi</b><br>Putra dari Bapak Hadi Wijanarko & Ibu Vinie Nurwachjunie</p><p class="center">&</p><p><b>Yholanda Regita Hariyanto</b><br>Putri dari Bapak Sugeng Hariyanto & Ibu Anik Rahayu</p><button class="pill" onclick="window.open('https://instagram.com/','_blank')">Instagram</button>`,'YHOLA & ARDAN UTK POP UP.png');
else if(id==='story')popup('Cerita Kami',`<img class="photo" src="gallery/story.jpg"><p>Berawal dari sebuah pertemuan di tahun 2018, di kampus yang sama, tanpa pernah menyangka bahwa pertemuan sederhana itu akan membawa kami sampai sejauh ini.</p><p>Di penghujung tahun 2019, kami memutuskan untuk melangkah bersama dan mulai berkomitmen untuk saling menemani.</p><p>Kami adalah dua pribadi dengan karakter yang cukup berbeda. Yhola yang cerewet, aktif, dan selalu menyukai keramaian, sementara Ardan lebih menyukai ketenangan. Namun, justru dari perbedaan itulah kami belajar untuk saling memahami, melengkapi, dan menikmati setiap perjalanan bersama.</p><p>Selama tujuh tahun, Ardan cukup sabar menghadapi segala tingkah kesayangannya ini. Ada banyak cerita, tawa, perbedaan, dan momen sederhana yang akhirnya menjadi bagian dari perjalanan kami.</p><p>Kini, kami berharap cerita ini tidak berhenti sampai di sini. Semoga romansa yang telah kami bangun terus membara, dipenuhi canda tawa, kasih sayang, dan kebahagiaan dalam setiap langkah yang akan kami jalani bersama.</p>`,'LOVE STORY UTK POP UP.png');
else if(id==='date')popup('Date & Venue',`<img class="photo" src="gallery/venue.jpg"><p class="center"><b>22 November 2026</b></p><p><b>Akad</b><br>08:00–09:00 WIB</p><p><b>Resepsi</b><br>10:00–12:00 WIB</p><p><b>Estusae Cafe, Trawas, Mojokerto</b><br>Sendang, Penanggungan, Kec. Trawas, Kabupaten Mojokerto, Jawa Timur 61375</p><p><b>Dress Code</b><br>Pakaian Ternyaman, Versi Terbaikmu</p><button class="pill" onclick="window.open('https://maps.app.goo.gl/j8p8AiPEjb7ygjZT6','_blank')">Google Maps</button>`,'DATE & VENUE UTK POP UP.png');
else if(id==='gallery')popup('Gallery',`<div class="gallery"><img src="gallery/C0009T01.JPG"><img src="gallery/C0006T01.JPG"><img src="gallery/C0007T01.JPG"><img src="gallery/C0005T01.JPG"></div>`,'GALLERY UTK POP UP.png');
else if(id==='gift')popup('Gift',`<p>Kehadiran dan doa restumu sudah menjadi hadiah yang sangat berarti bagi kami. Jika berkenan memberikan tanda kasih, berikut rekening yang dapat digunakan:</p><div class="accounts">${acc('BRI','067101498677509','Yholanda Regita Hariyanto')}${acc('MANDIRI','1400022970561','Yholanda Regita Hariyanto')}${acc('BCA','6155469025','Syahfardan Al Hilal Havi')}</div><p><b>Kirim hadiah</b><br>Dsn. Ketok Ds. Tunggalpager RT.02 RW.05 Kec. Pungging Kab. Mojokerto 61384<br>(Pagar Kipas Hitam)</p>`,'GIFT UTK POP UP.png');
else if(id==='rsvp')popup('RSVP',`<div class="form"><input id="rn" placeholder="Nama"><div class="choices"><button id="ry" onclick="choice(true)">Hadir</button><button id="rn2" onclick="choice(false)">Tidak Hadir</button></div><div id="count"><input type="number" min="1" max="10" placeholder="Jumlah tamu"></div><textarea rows="4" placeholder="Ucapan (opsional)"></textarea><button class="pill" onclick="alert('RSVP demo tersimpan. Integrasi Google Sheets/Form dapat dipasang berikutnya.')">Kirim RSVP</button></div>`,'RSVP UTK POP UP.png');
else if(id==='chair')popup('Pesan Kecil untukmu',`<p><b>Hai! 🤍</b></p><p>Terima kasih ya sudah jadi salah satu orang baik yang kami kenal.</p><p>Senang pernah dipertemukan dan berbagi cerita denganmu.</p><p>Sampai ketemu di hari bahagia kami!</p>`,'POP UP PENDEK.png')}
function acc(bank,num,name){return `<div class="account"><button onclick="navigator.clipboard&&navigator.clipboard.writeText('${num}')">Copy</button><b>${bank}</b>${num}<br>a/n ${name}</div>`};window.choice=v=>{$('ry').classList.toggle('on',v);$('rn2').classList.toggle('on',!v);$('count').style.display=v?'block':'none'};
$('infoBtn').onclick=()=>popup('Cara Menjelajah',`<p>👋 Hai, <b>${guest}</b>!</p><p>Bingung mulai dari mana? Di halaman ini ada beberapa bagian yang bisa kamu klik untuk melihat cerita kami. Coba eksplor satu-satu. Siapa tahu ada cerita kecil yang kamu temukan 🤍</p><p><b>YHOLA & ARDAN</b> — tentang kami</p><p><b>Cerita Kami</b> — cerita kita</p><p><b>Date & Venue</b> — hari dan tempat untuk merayakan cinta kami</p><p><b>Gallery</b> — potret kecil cerita kami 📷</p><p><b>Gift</b> — tanda kasihmu</p><p><b>RSVP</b> — sampai jumpa di hari bahagia kami 🤍</p>`,'INFO.png');
$('hand').addEventListener('animationend',()=>$('hand').classList.add('hidden'));
